In [2]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.random.rand(2,3)


array([[4.08736584e-01, 2.47580288e-01, 9.73682717e-01],
       [7.22615571e-01, 9.78750865e-01, 5.59813153e-04]])

In [11]:
np.random.randn(2,3)


array([[-2.18352998, -0.93591349,  0.56944364],
       [-0.27531838,  0.41616475, -0.22434287]])

In [12]:
np.random.randint(0,10,5)


array([6, 8, 5, 2, 3], dtype=int32)

In [13]:
np.random.randint(0,10,5)


array([3, 1, 3, 0, 3], dtype=int32)

In [14]:
np.random.randint(0,10,5)

array([2, 9, 2, 8, 7], dtype=int32)

In [15]:
np.random.randint(0,10,5)


array([4, 8, 9, 0, 9], dtype=int32)

In [17]:
arr = np.arange(55,65)
print(arr)
print(arr>58)
print(arr[arr>58])


[55 56 57 58 59 60 61 62 63 64]
[False False False False  True  True  True  True  True  True]
[59 60 61 62 63 64]


In [18]:
np.random.uniform(10,50,5)

array([26.52220167, 34.72731913, 18.4932937 , 42.16555937, 21.82337825])

In [19]:
np.random.normal(50,5,5)

array([56.91726504, 52.01143101, 52.65311676, 49.11786679, 51.93565882])

In [22]:
np.random.seed(42)

In [ ]:
filter = arr>58
print(arr[filter])

[59 60 61 62 63 64]
