In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.random.rand(2,3)


array([[0.25567735, 0.97049783, 0.61369163],
       [0.33942437, 0.69954532, 0.70961992]])

In [21]:
np.random.randn(2,3)


array([[-0.73871609, -0.86017067,  0.37486322],
       [-1.57888422,  0.51036211, -0.3459314 ]])

In [22]:
np.random.randint(0,10,5)


array([9, 7, 9, 4, 5], dtype=int32)

In [23]:
np.random.randint(0,10,5)


array([8, 3, 5, 4, 3], dtype=int32)

In [24]:
np.random.randint(0,10,5)

array([1, 0, 4, 5, 4], dtype=int32)

In [25]:
np.random.randint(0,10,5)


array([5, 8, 9, 4, 6], dtype=int32)

In [28]:
arr = np.arange(55,65)
print(arr)
print(arr>58)
print(arr[arr>58])


[55 56 57 58 59 60 61 62 63 64]
[False False False False  True  True  True  True  True  True]
[59 60 61 62 63 64]


In [30]:
filter = arr>58
print(arr[filter])

[59 60 61 62 63 64]
